site_name: YAMS
docs_dir: docs
theme:
  name: material
  highlightjs: true
plugins:
  - callouts
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - nl2br
  - pymdownx.details
  - pymdownx.superfences